apiVersion: v1
name: emrserverless-chart
description: A Helm chart for the ACK service controller for Amazon EMR Serverless (EMRServerless)
version: 0.0.0-non-release-version
appVersion: 0.0.0-non-release-version
home: https://github.com/aws-controllers-k8s/emrserverless-controller
icon: https://raw.githubusercontent.com/aws/eks-charts/master/docs/logo/aws.png
sources:
  - https://github.com/aws-controllers-k8s/emrserverless-controller
maintainers:
  - name: ACK Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/ack-admin
  - name: EMRServerless Admins
    url: https://github.com/orgs/aws-controllers-k8s/teams/emrserverless-maintainer
keywords:
  - aws
  - kubernetes
  - emrserverless
